### ISSUE TITLE
mac os error

### ISSUE THREAD

**Issue by krakiun** [nobodyzxc/RemoveAppAD#2]
Usage: bash ./main.sh [app.apk]
(base) admin@boss RemoveAppAD % ./main.sh 17TRACK.apk 
I: Using Apktool 2.9.0 on 17TRACK.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /Users/admin/Library/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
xargs: illegal option -- d
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
             [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
             [-s size] [utility [argument ...]]
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: 17TRACK_no_ad.apk
source:
	/Users/admin/Desktop/remove_ads/RemoveAppAD
zipalign location: PATH 
	/Users/admin/Library/Android/sdk/build-tools/31.0.0/zipalign
keystore:
	[0] 161a0018 /private/var/folders/_h/d0hbth5d2wld3grgyng3xxb80000gn/T/temp_15652998510530151820_debug.keystore (DEBUG_EMBEDDED)

01. 17TRACK_no_ad.apk

	SIGN
	file: /Users/admin/Desktop/remove_ads/RemoveAppAD/17TRACK_no_ad.apk (66.19 MiB)
	checksum: a59636e0f89ac60060dc98b1afdb1f4f291ee24ad25761fa5dfb36893b51b07b (sha256)
	- zipalign success
	- sign success

	VERIFY
	file: /Users/admin/Desktop/remove_ads/RemoveAppAD/17TRACK_no_ad.apk (66.58 MiB)
	checksum: 94e813fa7360b6f8970d08f25bd99e700b1f4bed24045132703c5d714cb66434 (sha256)
	- zipalign verified
	- signature verified [v1, v2] 
		2 warnings
		Subject: CN=Android Debug, OU=Android, O=US, L=US, ST=US, C=US
		SHA256: 1e08a903aef9c3a721510b64ec764d01d3d094eb954161b62544ea8f187b5953 / SHA256withRSA
		Expires: Thu Mar 10 22:10:05 EET 2044

[Fri Oct 13 05:54:17 EEST 2023][v1.0.0]
Successfully processed 1 APKs and 0 errors in 5.90 seconds.
(base) admin@boss RemoveAppAD % ls
17TRACK.apk		README.md		apktool.jar		sign.jar
17TRACK_no_ad.apk	apktool			main.sh
(base) admin@boss RemoveAppAD %

**Comment by nobodyzxc** [comment]
https://stackoverflow.com/questions/71409366/how-do-i-work-around-macos-x-not-having-xargs-d

**Comment by krakiun** [comment]
i solved in this way :
```
    grep -lR "\->loadAd" "${APK%.*}" | while IFS= read -r line; do
        sed -i '' '/\->loadAd/d' "$line"
    done
    ```
